### ISSUE TITLE
Feature request: support for texts with multiple sentences

### ISSUE THREAD

**Issue by dtchang** [discopy/discopy#143]
Many NLP tasks require the handling of texts with multiple sentences, with each text as a unit and the text meaning formed from sentence meanings in the text. An example is the sentiment classification of movie reviews, each of which is expressed as a text with multiple sentences.

**Comment by toumix** [comment]
Thanks for your interest in DisCoPy! Diagrams for text with multiple sentences is still an active area of theoretical research, see e.g. Coecke's [Mathematics of text structure](https://arxiv.org/abs/1904.03478). On the practical side, it's not completely clear yet how to implement this kind of theory. Do you have specific ideas for features you would like?

For now, the best we can do is just tensor the diagrams for each sentence independently. Obviously this is not satisfactory, as we would like to link these sentences together in some way. One approach would be to turn the output of a named entity recognition engine, e.g. [neuralcoref](https://spacy.io/universe/project/neuralcoref), into a diagram for the text. Would that be answering your request?

**Comment by dtchang** [comment]
Thank you for your response. I've studied DisCoCirc and agree that it's not clear if it is ready to be implemented, or how it should be implemented on top of or on the side of DisCoCat, which is a clean and consistent application of category theory.

The approach to turn the output of a named entity recognition engine into a string diagram for the text is a good one for text with sentences that have co-references, and would answer my request. 

For other types of text, e.g. a product review with a list of comments (in sentences) that have no co-references, a different approach may be needed, especially if it preserves the identity of member sentences.

**Comment by dtchang** [comment]
The lambeq team is working on a new backend so that lambeq can be detached from DisCoPy. As such, this 'future' feature request is appropriate for lambeq (library for QNLP), but not for DisCoPy (toolkit for string diagrams). I'm closing the issue. Thanks.
