### ISSUE TITLE
Incorrect definition of transposition for `pregroup.Swap`

### ISSUE THREAD

**Issue by nikhilkhatri** [discopy/discopy#257]
Minimal example:
```
from discopy.grammar.pregroup import Word, Swap, Ty

n, s = Ty('n'), Ty('s')

bx1 = Word("Abc", s @ n)
bx2 = Swap(n, s)

(bx1 @ bx1.l @ bx2 @ bx2.l).draw()
```
yields:

<img width="621" alt="image" src="https://github.com/discopy/discopy/assets/24587718/3ee905a7-7e46-4231-a8cb-fd65db31808d">

I would expect `bx2.l` to yield `Swap(n.l, s.l)`.

Indeed, this is what I get when using DisCoPy 0.5.1.2, with the modified code to account for difference in conj vs transpose between 0.x and 1.x:
```
from discopy.grammar.pregroup import Word, Swap, Ty

n, s = Ty('n'), Ty('s')

bx1 = Word("Abc", s @ n)
bx2 = Swap(n, s)

(bx1 @ bx1.l.dagger() @ bx2 @ bx2.l.dagger()).draw()
```
<img width="627" alt="image" src="https://github.com/discopy/discopy/assets/24587718/7915e906-8faa-4784-bf9a-afe667661879">

This behaviour yields `AxiomError`s when trying to transpose pregroup diagrams.

My guess is that this is because `pregroup.Swap` inherits from `frobenius.Swap`, where types are self-dual.

**Comment by toumix** [comment]
Thanks for the issue, I can confirm this is bug 🐛 

```python
>>> from discopy.grammar.pregroup import *
>>> n, s = Ty('n'), Ty('s')
>>> (Box("f", Ty(), n @ s) >> Swap(n, s)).r.draw()
AxiomError                                Traceback (most recent call last)
[...]
AxiomError: Id(n.r @ s.r) does not compose with Swap(n, s): n.r @ s.r != n @ s.
```

What's worse is the bug itself did not raise any `AxiomError` because we bypass the composition checks in the `rotate` method.
