### ISSUE TITLE
Discopy import error

### ISSUE THREAD

**Issue by sujit4uwbslg** [discopy/discopy#268]
when I am trying to import "from discopy import *"
I am getting error:
**NameError: name 'Swap' is not defined**

I tried "from discopy.rigid import Swap" also but getting same problem. I went through the documentation as well, but in spite of this is the part of the package I am unable to import it. Help me

**Comment by toumix** [comment]
Can you provide some details on how you installed the package? Otherwise there is no way to reproduce the error you describe, it doesn't happen on my machine nor on the GitHub ones during continuous integration jobs.

**Comment by sujit4uwbslg** [comment]
I installed the package using pip: pip install discopy. I have tried to install other version also like "pip install discopy--0.3.0". But still it is not working. I don't know why it happening

**Comment by sujit4uwbslg** [comment]
for your reference I am mentioning the output:

NameError                                 Traceback (most recent call last)
[<ipython-input-2-4ae5b467b80a>](https://localhost:8080/#) in <cell line: 2>()
      1 from discopy import *
----> 2 swap=Swap(water,food)
      3 swap.draw(figsize=(2,2))

NameError: name 'Swap' is not defined

**Comment by toumix** [comment]
Thanks! In general it's necessary to give the steps to reproducing the error, in this case not only the way you installed but the program you're trying to run, otherwise I cannot magically guess what's going on...

Here the problem is indeed that `Swap` is not defined! Try:

```python
from discopy.symmetric import *
water, food = Ty("water"), Ty("food")
Swap(water, food).draw()
```
