### ISSUE TITLE
Change domain with a functor application

### ISSUE THREAD

**Issue by colltoaction** [discopy/discopy#281]
Hi everyone, I'm trying to apply a functor but it doesn't allow changing the diagram boundaries even when there is no internal inconsistency. I wrote this example and would like to ask your advice on accomplishing this. Notice this gives an AxiomError:

```py
from discopy.frobenius import Hypergraph as H, Id, Ob, Ty, Box, Spider, Functor, Category

b1 = Box("b1", Ty("x"), Ty("y"))
b2 = Box("b2", Ty("y"), Ty("z"))
b = b1 >> b2
f = Functor(lambda x: x, lambda b: {
    b1: Box("b1", Ty("y"), Ty("y")),
    b2: Box("b2", Ty("y"), Ty("z"))}[b])
f(b).draw()
```

```
discopy.utils.AxiomError: Id(x) does not compose with b1: x != y.
```

Thank you!

**Comment by toumix** [comment]
You need the image of the functor `F` on types and on boxes to be consistent, in the sense that `F(box.dom) == F(box).dom`.

In this case you need to send `x` to `y`:

```python
from discopy.monoidal import *
x, y, z = map(Ty, "xyz")
b1 = Box("b1", x, y)
b2 = Box("b2", y, z)
b = b1 >> b2
ar = {
    b1: Box("b1", y, y),
    b2: Box("b2", y, z)}
ob = {x: y, y: y, z: z}
f = Functor(ob, ar)
f(b).draw()
```

**Comment by colltoaction** [comment]
Let's say there is another `x` not in the boundary that I don't want to change.

I can only imagine plugging some other box on the left before applying `f` to achieve this. Is that correct? Thanks!

**Comment by toumix** [comment]
Indeed if you want a different image `F(x)` for the same type `x` used in different places, then what you're describing is not a functor `F` but an arbitrary diagram-valued function. 

> I can only imagine plugging some other box on the left before applying f to achieve this.

We can imagine a lot of things but you are correct in the sense that this closer to the way DisCoPy was intended to be used!

**Comment by colltoaction** [comment]
Ahá! This diagram-valued function is a parser, and I'm also trying to write the parser diagrammatically. I have it much more clear now, thanks!
